service: serverlessapplicationapi

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment: 
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: 'Allow'   
      Action:
        - dynamodb:*
      Resource: 'arn:aws:dynamodb:*:*:table/${self:custom.tableName}'


functions:
  GET_updatedText:
    handler: backend/endpoints/GET_updatedText.handler
    events: 
        - http:
            path: get-updatedtext/{requestID}
            method: GET
            cors: true  
  POST_processText:
    handler: backend/endpoints/POST_processText.handler
    events: 
        - http:
            path: post-processtext
            method: POST
            cors: true


resources: 
  Resources: 
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: requestID
            AttributeType: S
        KeySchema:
          - AttributeName: requestID
            KeyType: HASH

        BillingMode: PAY_PER_REQUEST 


plugins:
  - serverless-finch


custom:
  tableName: requestDataTable
  client:
    bucketName: sandbox-gasparet-serverless-application-api-frontend
    distributionFolder: frontend
    errorDocument: index.html